### ISSUE TITLE
Tool command and parameter information export

### ISSUE THREAD

**Issue by DiamondDragon** [GodelTech/CodeReview.Orchestrator#32]
#### DESCRIPTION
At the moment commands and parameters for tool(s) are described manually. It's suggested to eliminate manual work using the following approach:

* Each tool has command which exports support commands and parameters into JSON file. Reflection can be used to discover all options and associated attributes.
* `CodeReview.Templater` is used to create Markdown file from JSON file.

Suggested solution allows to have accurate information about parameters with minimal affords.

Here is possible format of exporting data:

```json

{
   "commands" :  [
      {
          "name" : "new",
          "isDefault" : true,
          "description" : "some description",
          "parameters" : [
               {
                   "shortName" : "s",
                   "longName" : "source",
                   "description" : "some description",
                   "isOptional" : true,
                   "defaultValue" : "some value"
               }
          ]
     },
    .....
   ]
}

```

Alternative option:

```json

{
   "commands" :  {
           "new" : {
            "isDefault" : true,
            "description" : "some description",
            "parameters" : {
                  "source" : {
                     "shortName" : "s",
                     "description" : "some description",
                     "isOptional" : true,
                     "defaultValue" : "some value"
                  }
             }
       }
 }

```

#### ADDITIONAL CONTEXT

It makes sense to create template which is compatible with [CodeReview.TemplateRenderer](https://github.com/GodelTech/CodeReview.TemplateRenderer). This template allows us to make sure that exported data format is easy to consume for rendering. Template should output information in markdown format.

**Comment by pNovikau** [comment]
Done: https://github.com/GodelTech/CodeReview.Orchestrator/pull/36
