### ISSUE TITLE
Improve Superset fork

### ISSUE THREAD

**Issue by DiamondDragon** [GodelTech/CodeReview.Orchestrator#35]
#### DESCRIPTION
The following repository contains fork of official Superset tool: https://github.com/GodelTech/superset/
It's suggested to add the following improvements:
* Merge changed from branch `monitor` to master.
* Add volume mount of `pgAdmin` tool to avoid issue with loosing connection settings after container is re-created. Example of required changes can be found [here](https://azuredevops.godeltech.com/DefaultCollection/DotNet%20Compliance/_git/CodeReview.Monitor?path=%2Fdocker-compose.yml&version=GBmaster&line=26&lineEnd=27&lineStartColumn=1&lineEndColumn=1&lineStyle=plain).

**Comment by agolovnev-godeltech** [comment]
Implemented and commited to master
